[package]
name = "rust_version"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
directories = "6.0.0"
display-info = "0.5.7"
eframe = "0.33.2"
egui = "0.33.2"
home = "0.5.12"
open = "5.3.3"
rfd = "0.16.0"
which = "8.0.0"
winit = "0.30.12"
